CREATE TABLE user (
  `GUID` char(36) COLLATE ascii_bin NOT NULL,
  `VER` bigint DEFAULT 0,
  `CREATIONTIMESTAMP` bigint NOT NULL,
  `FIRSTNAME` varchar(255) NOT NULL,
  `LASTNAME` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `USERNAME` varchar(255) NOT NULL,
  `ENABLED` bool NOT NULL DEFAULT true,
  `ROLE` VARCHAR(255) NOT NULL,
  PRIMARY KEY (GUID)
);